# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_connection_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='creator',
        ),
    ]
