# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_connection_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='connection',
            name='creator',
        ),
    ]
