# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.TextField()),
                ('item_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=0)),
                ('transaction_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SellerLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.TextField()),
                ('seller_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SellerQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField(default=0)),
                ('transaction_id', models.TextField()),
            ],
        ),
    ]
