# -*- coding: utf-8 -*-
<<<<<<< HEAD:octokart/logger/migrations/0002_message_timestamp.py
# Generated by Django 1.9.4 on 2016-04-14 21:19
=======
# Generated by Django 1.9.4 on 2016-04-15 17:19
>>>>>>> octokartseller moved to octokart:octokart/transactions/migrations/0001_initial.py
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
            ],
        ),
    ]
