# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_id',
            field=models.CharField(max_length=50),
        ),
    ]
